corca-ai/cds

.github/workflows/package-publish.yml
package.json

- ADCIO-
- VILL-
- npm package public으로 cds를 publish합니다

NONE) fix: fix ci for publish cds in NPM

---

package.json

- ADCIO-
- VILL-
NONE
- package.json의 publish config 때문에 github packages를 이용해서 cds가 publish 되는 문제가 있었습니다.
- 삭제해줍니다.
- 삭제하면 npm 기본 공식 레지스트리에 배포됩니다!

NONE) fix: fix publish config for npm publish

---

.github/workflows/package-publish.yml
package.json

- ADCIO-
- VILL-
- registry-url: 'https://npm.pkg.github.com' 때문에 github packages로 배포되는 문제가 있었습니다.
- 없으면 default로 npm package로 배포하게 됩니다.

NONE) fix: fix ci without registry url

---

package.json

- ADCIO-
- VILL-
NONE
- 현재 이미 github packages로 publish된 corca-ai/cds 패키지가 존재합니다.
- 완전 동일 이름으로 하면 패키지가 꼬일 수 있고 현재 ci에서도 다음과 같은 문제가 있습니다.
- npm packages에 이미 cds라는 이름이 너무 많이 사용되고 있습니다.
```
npm error code E402
npm error 402 Payment Required - PUT https://registry.npmjs.org/@corca-ai%2fcds 
```
[corca-design-system](https://www.npmjs.com/package/corca-design-system) 이 이름으로는 publish 됩니다!

NONE) fix: fix name for duplication

---

package.json

- ADCIO-
- VILL-
v0.0.12를 릴리즈 합니다.

NONE) release: release 0.0.12

---

README.md

- ADCIO-
- VILL-
리드미를 작성했습니다.
혹시 추가로 작성하고 싶으신 내용이 있으시다면 알려주시면 반영하겠습니다! 🙇

NONE) docs: add readme

---

package.json
src/components/index.ts
src/index.ts

- ADCIO-
- VILL-
현재 design system을 설치해서 사용하려고 하면, 
Icon을 포함해 Table과 DatePicker namespace를 찾을 수 없다는 에러가 발생하고 있습니다. (* 사진 참고)
- 이유를 확인해보니 언급한 컴포넌트를 export 하고 있지 않아서, 트리쉐이킹 되었음을 확인했습니다.
- 실제로 빌드 결과물 파일(= dist/index.js)을 확인해보니, 언급한 컴포넌트가 빌드 결과물에 포함되지 않았음을 확인했습니다.
- 언급한 컴포넌트를 export 하게끔 수정해주어 정상적으로 빌드 결과물에 포함되게끔 수정해주었습니다.
- cds 빌드 결과물을 rmp에 적용했더니 위와 같이 아이콘이 잘 보여지고 있는 것을 확인했습니다.
- 해당 브랜치에서 pnpm build를 한다.
- rmp node_modules의 @corca-ai/design-system 라이브러리의 dist 폴더를 빌드 결과물로 변경한다.
- Icon, Table, DatePicker가 정상적으로 적용되는지 확인한다.

NONE) fix: fix component export issue

---

package.json
pnpm-lock.yaml
src/components/Topbar/ProfileMenu.tsx
src/stories/Topbar.stories.tsx

- ADCIO-3707
- VILL-
- 최신 prettier 버전이 eslint 버전과 호환되지 않는 문제가 있습니다.
- Topbar의 타입 또한 수정해줍니다.
- 패키지 버전을 올려줍니다.
- storybook에도 타입 수정 사항을 반영해줍니다.

ADCIO-3707) fix: fix prettier version and type in topbar

---

package.json
src/components/Topbar/ProfileMenu.tsx
src/components/Topbar/index.tsx

- ADCIO-
- VILL-
- TopBar의 icon 타이핑이 적절하지 않아서 cds icon을 탑바에 사용하지 못하는 문제가 있습니다.
- 타입이 export되지 않아 패키지 밖에서 타입을 사용하지 못합니다

NONE) fix: fix typing

---

package.json
pnpm-lock.yaml
vite.config.ts

- ADCIO-
- VILL-
cds를 next.js ssr에서 사용했더니 위 에러가 발생했습니다.
- vite.config.js에서 rollupOptions.external에 emotion을 추가했더니 해결되었습니다. [[참고 링크]](https://github.com/JedWatson/react-select/issues/5555#issuecomment-1633112572)
- 추측: emotion 코드가 js로 트랜스파일링되지 않아서 발생한걸로 의심중
- rollupOptions.external에 들어간 라이브러리들을 devDependency로 변경합니다.

NONE) chore: fix emotion error

---

package.json
src/components/Select/SelectInput.tsx
src/stories/Select.stories.tsx

- ADCIO-4010
- VILL-
- input 창의 left section에 고정 아이콘이 있는 케이스가 필요합니다.
- 스토리북도 추가합니다.

ADCIO-4010) feat: add select with icon and story

---

package.json
src/components/Table/Tr.tsx
src/stories/Table.stories.tsx

- ADCIO-3917
- VILL-
table tr이 hover / pressed 되었는지 여부에 따라 background color가 달라져야 합니다.
- 피그마에 맞게 table tr이 hover / pressed 되었는지 여부에 따라 background color를 다르게 지정합니다.
- border color가 grey-50으로 잘못 지정되어 있었던 것을 grey-30으로 수정합니다.

ADCIO-3917) fix: fix table tr state style issue

---

package.json
src/components/Select/MultiSelect.tsx
src/components/Select/MultiSelectInput.tsx
src/components/Select/OptionList.tsx
src/components/Select/Select.tsx
src/components/Select/SelectInput.tsx
src/components/Select/index.ts
src/stories/Select.stories.tsx

[디자인](https://www.figma.com/design/8OFszRIlYmDIH5iUiHAeNI/ADCIO?node-id=5409-50231&t=LeBk7qXjSt3TYCZv-4)
- ADCIO-4008
- VILL-
- multi select
- 검색 기능 추가
- 기존과 달리 아이템 선택후에도 list 창 닫히지 않음
- 성지님에게 실제 동작 QA 최종으로 완료했습니다!

ADCIO-4008) feat: add multi select

---

package.json
src/components/Select/MultiSelect.tsx
src/components/Select/MultiSelectInput.tsx
src/components/Select/OptionList.tsx
src/components/Select/Select.tsx

- ADCIO-
- VILL-
- select의 value로 string만 사용할 수 있었습니다.
- number도 이용 가능하도록 수정합니다.
- value가 label로 사용될때 String으로 캐스팅되도록 수정해줍니다.

Fix) fix: fix select default type to use number and string

---

package.json
src/components/Select/MultiSelect.tsx

- ADCIO-3975
- VILL-
- multi select initial value 값 설정이 안되는 문제가 있었습니다
- useState 내에서 초기 값을 함수형으로 설정해서 컴포넌트 초기 렌더링 시에 단일 실행되도록 하여 init value를 전달합니다.

NONE) feat: add multi select init value available

---

package.json
src/components/Select/MultiSelectInput.tsx
src/components/Select/OptionList.tsx
src/components/Select/SelectInput.tsx

- ADCIO-3975
- VILL-
- button 엘리먼트가 button 엘리먼트를 nesting 해서 에러가 나고 있습니다.
- button을 div로 바꾸고 스토리북에서 테스트합니다.

ADCIO-3975) feat: fix element tag

---

package.json
src/components/Select/MultiSelectInput.tsx

- ADCIO-
- VILL-
- button이 div를 nesting하고 있어 에러가 납니다.
```
Expected server HTML to contain a matching <div> in <button>.
at div
at eval
```
- <button> 내부에 <div>를 포함하는 것은 HTML5 표준에 위배됩니다. 
- button을 div로 바꿔줍니다

NONE) fix: fix button to element

---

package.json
src/components/Select/MultiSelect.tsx

- ADCIO-
- VILL-
- onSelect를 외부에서 커스터마이징하여 사용했을때 실제 select한 값과 select item ui가 일부 다르게 보이는 문제가 있습니다.
- 수정합니다
- 일부 dependency array에 빠진 부분도 추가해줍니다.

NONE) fix: fix multiselect onselect

---

package.json
src/components/Select/MultiSelect.tsx
src/components/Select/MultiSelectInput.tsx

- ADCIO-
- VILL-
- mulit select에서 edge case를 발견했습니다.
- 특이 케이스 - 1개 선택 후 전체 삭제 로직시 default 값(1개)으로 자동 설정 하는 경우
- dependency array를 수정해줍니다.

NONE) fix: fix multi select single pick

---

package.json
src/components/Table/Td.tsx
src/components/Table/Th.tsx
src/components/Table/index.tsx
src/stories/Table.stories.tsx

- ADCIO-
- VILL-
- left border와 right border 그리고 background color style 추가가 필요합니다.
- prop으로 추가합니다
- storybook에도 스타일 추가된 테이블을 추가합니다.

NONE) feat: add table styling props

---

package.json
src/components/Badge/index.tsx
src/stories/Badge.stories.tsx

- ADCIO-
- VILL-
- badge width가 고정이었습니다.
- label이 길어질경우 ui가 깨지는 현상이 있었습니다
- 수정 후 스토리북도 추가해줍니다.

NONE) fix: fix badge style

---

package.json
src/components/Table/index.tsx
src/components/index.ts
src/stories/Table.stories.tsx

[ADCIO-4374](https://corca.atlassian.net/browse/ADCIO-4374)
- table 컴포넌트에서 export하고 있는 상수들이 빌드 결과물에 포함되지 않았습니다.
- components/index.ts export하지 않고 있어서 발생하는 이슈입니다.
- 빌드 결과물에 포함되게끔 수정하고, 버전 0.028을 올립니다.
- 로컬에서 빌드 결과물 이상 없는 것을 확인했습니다.

ADCIO-4374) chore: export table constant

---

src/components/Filter/DateRange.tsx
src/stories/DatePicker.stories.tsx
src/utils/date.ts

- ADCIO-
- VILL-
- support locale을 DatePickerLocale로 수정해줘야합니다.
- 빌드 에러가 납니다.

NONE) fix: fix support locale to date range picker locale

---

src/components/Filter/DateRange.tsx
src/stories/Filter.stories.tsx

- ADCIO-
- VILL-
- build를 위해 타이핑 수정이 필요합니다.

NONE) fix: fix type err

---

vite.config.ts

The commit message suggests excluding story files from the dts generation process.
- ADCIO-
- VILL-
빌드 시 storybook도 같이 타입체크를 해서 타입에러가 발생
불필요한 storybook 코드들도 dist에 포함됨
빌드 시 storybook 파일은 무시
- 속도 1초 증가 : 3.52s -> 2.62s 👍 
- stories 파일 dist에 무시함

feat: exclude story files from dts generation

---

package.json

- [ADCIO-4759](https://corca.atlassian.net/browse/ADCIO-4769)
- VILL-

ADCIO-4769) fix: update npm dependency to version 0.0.31

---

.github/workflows/package-publish.yml
package.json

chore: remove package type from package.json and update npm dependency

---

package.json
src/legacy/components/Select/MultiSelectInput.tsx
src/legacy/stories/Select.stories.tsx

- ADCIO-
- VILL-
- 기존 multi select에서 placeholder를 사용할 수 없습니다

NONE) chore: fix multi select placeholder
